### ISSUE TITLE
win10下载失败

### ISSUE THREAD

**Issue by WtyFile** [gxtrobot/bustag#15]
serving on 0.0.0.0:8000 view at http://127.0.0.1:8000
start download
Job "download (trigger: date[2019-09-16 23:39:29 CST], next run at: 2019-09-16 23:39:29 CST)" raised an exception
Traceback (most recent call last):
  File "lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
  File "bustag\app\schedule.py", line 18, in download
KeyError: 'download.root_path'

**Comment by vickersxu** [comment]
same question

**Comment by vickersxu** [comment]
> serving on 0.0.0.0:8000 view at http://127.0.0.1:8000
> start download
> Job "download (trigger: date[2019-09-16 23:39:29 CST], next run at: 2019-09-16 23:39:29 CST)" raised an exception
> Traceback (most recent call last):
> File "lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
> File "bustag\app\schedule.py", line 18, in download
> KeyError: 'download.root_path'

i solved it ，
add this in config.ini

[download]
root_path = https://www.cdnbus.bid
count = 300
interval = 1800

**Comment by 572705296** [comment]
me too.

**Comment by lovecg1314** [comment]
put the config.ini  in to your "data"Folder。
you can download this ini at code。

**Comment by WtyFile** [comment]
i find the question. it's because your data/config.ini has no messages. you should add 
[download]
root_path = https://www.cdnbus.bid
count = 300

then start it again.
by the way,all the Movies have mosaic. i don't like it very much
@vickersxu @572705296
